module.exports = [
  {
    id: 1,
    name: "Alice Johnson",
    designation: "Software Engineer",
    phone: "+1-555-1234",
  },
  {
    id: 2,
    name: "Bob Smith",
    designation: "Product Manager",
    phone: "+1-555-5678",
  },
  {
    id: 3,
    name: "Carol White",
    designation: "UX Designer",
    phone: "+1-555-9101",
  },
  {
    id: 4,
    name: "David Brown",
    designation: "Data Scientist",
    phone: "+1-555-1121",
  },
  {
    id: 5,
    name: "Eve Davis",
    designation: "Marketing Specialist",
    phone: "+1-555-3141",
  },
  {
    id: 6,
    name: "Frank Miller",
    designation: "DevOps Engineer",
    phone: "+1-555-5161",
  },
  {
    id: 7,
    name: "Grace Lee",
    designation: "HR Manager",
    phone: "+1-555-7181",
  },
  {
    id: 8,
    name: "Hank Wilson",
    designation: "Business Analyst",
    phone: "+1-555-9201",
  },
  {
    id: 9,
    name: "Ivy Clark",
    designation: "Project Coordinator",
    phone: "+1-555-1223",
  },
  {
    id: 10,
    name: "Jack Lewis",
    designation: "Graphic Designer",
    phone: "+1-555-3245",
  },
  {
    id: 11,
    name: "Karen Walker",
    designation: "Sales Executive",
    phone: "+1-555-5267",
  },
  {
    id: 12,
    name: "Larry Hall",
    designation: "Network Engineer",
    phone: "+1-555-7289",
  },
  {
    id: 13,
    name: "Mona King",
    designation: "Accountant",
    phone: "+1-555-9311",
  },
  {
    id: 14,
    name: "Nina Scott",
    designation: "Content Writer",
    phone: "+1-555-1334",
  },
  {
    id: 15,
    name: "Oscar Reed",
    designation: "IT Support Specialist",
    phone: "+1-555-3356",
  },
  {
    id: 16,
    name: "Paul Young",
    designation: "Operations Manager",
    phone: "+1-555-5378",
  },
  {
    id: 17,
    name: "Quincy Adams",
    designation: "Financial Analyst",
    phone: "+1-555-7390",
  },
  {
    id: 18,
    name: "Rita Nelson",
    designation: "Executive Assistant",
    phone: "+1-555-1423",
  },
  {
    id: 19,
    name: "Sam Parker",
    designation: "Customer Support",
    phone: "+1-555-3445",
  },
  {
    id: 20,
    name: "Tina Baker",
    designation: "Legal Advisor",
    phone: "+1-555-5467",
  },
  {
    id: 21,
    name: "Ulysses Harris",
    designation: "Software Engineer",
    phone: "+1-555-1234",
  },
];
